# Generated by Django 4.2.7 on 2025-06-02 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='父项目ID')),
                ('main_project', models.CharField(blank=True, max_length=200, null=True, verbose_name='备案项目主项目')),
                ('main_project_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='主项目地址')),
                ('sub_project', models.CharField(blank=True, max_length=200, null=True, verbose_name='子项目')),
                ('rectification_details', models.TextField(blank=True, null=True, verbose_name='整改完成情况明细（完成几项）')),
                ('inspection_details', models.TextField(blank=True, null=True, verbose_name='巡查日期明细（共几次）')),
                ('project_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目编号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('construction_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='工程期限')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开工日期')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='竣工日期')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='地址')),
                ('construction_unit', models.CharField(blank=True, max_length=200, null=True, verbose_name='建设单位')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('contractor', models.CharField(blank=True, max_length=200, null=True, verbose_name='施工单位')),
                ('contractor_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='施工单位联系人')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='业主')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='面积')),
                ('construction_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='建安造价')),
                ('on_site_records', models.TextField(blank=True, null=True, verbose_name='现场开单记录明细（共几项）')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '子项目详细信息',
                'verbose_name_plural': '子项目详细信息',
                'db_table': 'sub_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
