# Generated by Django 4.2.7 on 2025-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='main_construction_unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='大项目建设单位'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='sub_project_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='子项目ID'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='inspection_details',
            field=models.IntegerField(blank=True, null=True, verbose_name='巡查日期明细（共几次）'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='on_site_records',
            field=models.IntegerField(blank=True, null=True, verbose_name='现场开单记录明细（共几项）'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='rectification_details',
            field=models.IntegerField(blank=True, null=True, verbose_name='整改完成情况明细（完成几项）'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='sub_project',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='名称'),
        ),
    ]
