# Generated by Django 4.2.7 on 2025-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_subproject_main_construction_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='项目状态'),
        ),
    ]
