# Generated by Django 4.2.7 on 2025-06-23 03:09

from django.db import migrations


def update_status_codes(apps, schema_editor):
    """将旧的状态码转换为新的状态码"""
    SubProject = apps.get_model('projects', 'SubProject')
    
    # 状态码映射：旧码 -> 新码
    status_mapping = {
        '0': '1',   # 未开始 -> 正常
        '10': '1',  # 进行中 -> 正常  
        '20': '2',  # 已完结 -> 完成
        '30': '4'   # 已停工 -> 停工
    }
    
    for project in SubProject.objects.all():
        if project.status in status_mapping:
            project.status = status_mapping[project.status]
            project.save()


def reverse_status_codes(apps, schema_editor):
    """回滚操作：将新状态码转换回旧状态码"""
    SubProject = apps.get_model('projects', 'SubProject')
    
    # 反向映射：新码 -> 旧码（可能不是一对一的）
    reverse_mapping = {
        '1': '10',  # 正常 -> 进行中
        '2': '20',  # 完成 -> 已完结
        '4': '30'   # 停工 -> 已停工
    }
    
    for project in SubProject.objects.all():
        if project.status in reverse_mapping:
            project.status = reverse_mapping[project.status]
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_subproject_status'),
    ]

    operations = [
        migrations.RunPython(update_status_codes, reverse_status_codes),
    ]
